import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import { useContext } from "react";
import { AppContext } from "../context/context";
import Login from "../components/Login";
import Widget from "../components/Widget";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { currentAccount } = useContext(AppContext);

  if (!currentAccount) return <Login />;
  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex max-w-7xl mx-auto px-5 ">
        <Sidebar />
        <Feed />
        <Widget />
      </main>
    </>
  );
}
